### ISSUE TITLE
In the dftU part of schema lda_plus_u is missing

### ISSUE THREAD

**Issue by afonari** [QEF/qexsd#8]
Thus LDA+U calculations cannot be enabled, see: https://github.com/QEF/qexsd/blob/master/examples/PW/FeO_LDAU_standard.xml and related https://github.com/QEF/qexsd/blob/master/examples/PW/FeO_LDAU_standard.in which actually is not an LDA+U calculation.

**Comment by afonari** [comment]
I just confirmed that without explicit lda_plus_u=.true. LDA+U is not enabled, see attached.



[Archive.zip](https://github.com/QEF/qexsd/files/1125598/Archive.zip)

**Comment by pietrodelugas** [comment]
I corrected the example and the converter which was not doing what it was supposed to do. I also propagated changes from  QEF/qexsd repo to the bin/qexsd directory within the  QEF/qe_schrodinger/ repository

**Comment by afonari** [comment]
Sounds good, Pietro, thanks a lot!
